
server:
  port: 8080

logging:
  level:
    com.ironia.ms.email: TRACE
#    root: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: banco123

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: *********@gmail.com
    password: ************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    addresses: *****************
    queue: ms.email